apiVersion: v1
kind: Secret
metadata:
  name: {{ template "maalfrid.fullname" . }}-rethinkdb-env
  labels:
    app: {{ template "maalfrid.name" . }}
    chart: {{ template "maalfrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_USER: {{ .Values.config.rethinkdb.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.config.rethinkdb.password | b64enc | quote }}
