kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "maalfrid.fullname" . }}-rethinkdb-env
  labels:
    app: {{ template "maalfrid.name" . }}
    chart: {{ template "maalfrid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DB_HOST: {{ .Values.config.rethinkdb.host | quote }}
  DB_PORT: {{ .Values.config.rethinkdb.port | quote }}
  DB_NAME: {{ .Values.config.rethinkdb.name | quote }}
