apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  {{ include "maalfrid-aggregator-client.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maalfrid-aggregator-client.name" . }}
    helm.sh/chart: {{ include "maalfrid-aggregator-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  suspend: {{ .Values.suspend }}
  schedule: {{ .Values.cronExpression | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "maalfrid-aggregator-client.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
{{ toYaml .Values.config.command | indent 16 }}
              env:
                - name: HOST
                {{- if .Values.config.aggregatorService.host }}
                  value: {{ .Values.config.aggregatorService.host | quote }}
                {{- else }}
                  valueFrom:
                    configMapKeyRef:
                      name: {{ template "maalfrid-aggregator-client.configPrefix" . }}
                      key: aggregatorService.host
                {{- end }}
                - name: PORT
                {{- if .Values.config.aggregatorService.port }}
                  value: {{ .Values.config.aggregatorService.port | quote }}
                {{- else }}
                  valueFrom:
                    configMapKeyRef:
                      name: {{ template "maalfrid-aggregator-client.configPrefix" . }}
                      key: aggregatorService.port
                {{- end }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
    {{- with .Values.nodeSelector }}
            nodeSelector:
{{ toYaml . | indent 14 }}
    {{- end }}
    {{- with .Values.affinity }}
            affinity:
{{ toYaml . | indent 14 }}
    {{- end }}
    {{- with .Values.tolerations }}
            tolerations:
{{ toYaml . | indent 14 }}
    {{- end }}
