# Default values for maalfrid-initdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: norsknettarkiv/maalfrid-initdb
  tag: ""
  pullPolicy: IfNotPresent
  restartPolicy: Never

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

annotations: {}

config:
  rethinkdb:
    host: ""
    port: ""
    user: "admin"
    password: ""
  create:
    database: "maalfrid"
    user: "maalfrid"
    password: "changeme"

global:
  maalfrid:
    rethinkdb:
      host: ""
      port: ""
      name: ""
