apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "maalfrid-aggregator-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maalfrid-aggregator-service.name" . }}
    helm.sh/chart: {{ include "maalfrid-aggregator-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "maalfrid-aggregator-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "maalfrid-aggregator-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 3011
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "maalfrid.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DB_HOST
              value: {{ default .Values.global.maalfrid.rethinkdb.host .Values.config.rethinkdb.host | quote }}
            - name: DB_PORT
              value: {{ default .Values.global.maalfrid.rethinkdb.port .Values.config.rethinkdb.port | quote }}
            - name: DB_NAME
              value: {{ default .Values.global.maalfrid.rethinkdb.name .Values.config.rethinkdb.name | quote }}
            - name: PORT
              value: "3011"
            - name: LANGUAGE_SERVICE_HOST
            {{- if .Values.config.languageDetector.host }}
              value: {{ .Values.config.languageDetector.host | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "maalfrid.configPrefix" . }}
                  key: languageDetector.host
            {{- end }}
            - name: LANGUAGE_SERVICE_PORT
            {{- if .Values.config.languageDetector.port }}
              value: {{ .Values.config.languageDetector.port | quote }}
            {{- else }}
              valueFrom:
                configMapKeyRef:
                  name: {{ template "maalfrid.configPrefix" . }}
                  key: languageDetector.port
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
