.aggregator-job: &aggregator-job
  name: maalfrid-aggregator-client
  version: 0.6.0
  repository: file://../maalfrid-aggregator-client/
  tags:
  - aggregatorJob

dependencies:
- <<: *aggregator-job
  alias: detect-job
- <<: *aggregator-job
  alias: aggregate-job
- <<: *aggregator-job
  alias: sync-job
- <<: *aggregator-job
  alias: statistics-job
