.aggregator-job: &aggregator-job
  name: maalfrid-aggregator-job
  version: 0.5.1
  repository: file://../maalfrid-aggregator-job/
  tags:
  - aggregatorJob

dependencies:
- <<: *aggregator-job
  alias: detect-job
- <<: *aggregator-job
  alias: aggregate-job
- <<: *aggregator-job
  alias: sync-seeds-job
- <<: *aggregator-job
  alias: sync-entities-job
