
nameOverride: ""
fullnameOverride: ""

config:
  languageDetector:
    host: ""
    port: ""

  aggregatorService:
    host: ""
    port: ""

  rethinkdb:
    host: ""
    port: ""
    name: ""
    user: ""
    password: ""

default:
  languageDetector:
    host: "maalfrid-language-detector"
    port:  "8672"

  aggregatorService:
    host: "maalfrid-aggregator-service"
    port: "3011"

  rethinkdb:
    host: "localhost"
    port: "28015"
    name: "maalfrid"
    user: "maalfrid"
    password: "maalfrid"

maalfrid-initdb:
  config:
    rethinkdb:
      user: "admin"
      password: ""
    create:
      database: "maalfrid"
      user: "maalfrid"
      password: "maalfrid"
