nameOverride: ""
fullnameOverride: ""

config:
  languageDetector:
    host: ""
    port: ""

  aggregatorService:
    host: ""
    port: ""

  rethinkdb:
    user: ""
    password: ""

default:
  languageDetector:
    host: "maalfrid-language-detector"
    port:  "8672"

  aggregatorService:
    host: "maalfrid-aggregator-service"
    port: "3011"

  rethinkdb:
    user: "maalfrid"
    password: "maalfrid"

maalfrid-language-detector:
  config:
    count: 5
    maxRecvMsgSize: "10000000"

maalfrid-initdb:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  config:
    rethinkdb:
      user: "admin"
      password: ""
    create:
      database: "maalfrid"
      user: "maalfrid"
      password: "maalfrid"

detect-job:
  config:
    command:
      - detect

aggregate-job:
  config:
    command:
      - aggregate

sync-job:
  config:
    command:
      - sync

statistics-job:
  config:
    command:
      - filter


global:
  maalfrid:
    rethinkdb:
      host: $(NODE_NAME)
      port: 28015
      name: "maalfrid"
