
nameOverride: ""
fullnameOverride: ""

config:
  languageDetector:
    host: ""
    port: ""

  aggregatorService:
    host: ""
    port: ""

  rethinkdb:
    host: ""
    port: ""
    name: ""
    user: ""
    password: ""

default:
  languageDetector:
    host: "maalfrid-language-detector"
    port:  "8672"

  aggregatorService:
    host: "maalfrid-aggregator-service"
    port: "3011"

  rethinkdb:
    host: "localhost"
    port: "28015"
    name: "maalfrid"
    user: "maalfrid"
    password: "maalfrid"

maalfrid-initdb:
  config:
    rethinkdb:
      user: "admin"
      password: ""
    create:
      database: "maalfrid"
      user: "maalfrid"
      password: "maalfrid"

.aggregatorJob: &aggregatorJob
  # restartPolicy: "Never"
  # concurrencyPolicy: "Forbid"
  # failedJobsHistoryLimit: 1
  # successfulJobsHistoryLimit: 1
  suspend: true

detect-job:
  <<: *aggregatorJob
  config:
    command:
    - detect

aggregate-job:
  <<: *aggregatorJob
  config:
    command:
    - aggregate

sync-job:
  <<: *aggregatorJob
  command:
  - sync
