connectors: null
enablePasswordDB: true
grpc:
  addr: 0.0.0.0:5000
  tlsCert: /etc/dex/tls/grpc/server/tls.crt
  tlsClientCA: /etc/dex/tls/grpc/ca/tls.crt
  tlsKey: /etc/dex/tls/grpc/server/tls.key
issuer: https://veidemann.local/dex
logger:
  format: text
  level: debug
oauth2:
  responseTypes:
  - code
  - token
  - id_token
  skipApprovalScreen: true
staticPasswords:
- email: admin@example.com
  hash: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
  userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
  username: admin
storage:
  config:
    inCluster: true
  type: kubernetes
web:
  allowedOrigins:
  - https://veidemann.local
  - https://localhost:4200
  http: 0.0.0.0:8080
staticClients:
- id: maalfrid-gui
  redirectURIs:
  - 'https://veidemann.local/maalfrid'
  - 'https://localhost:4200/maalfrid'
  name: 'Maalfrid GUI'
- id: maalfrid-api
  name: 'Maalfrid API'
  trustedPeers:
  - maalfrid-gui
- id: veidemann-dashboard
  redirectURIs:
  - "https://veidemann.local/veidemann/activity"
  - "https://localhost:4200/activity"
  name: "Veidemann Dashboard"
- id: veidemann-cli
  public: true
  name: "Veidemann CLI"
- id: veidemann-api
  name: "Veidemann API"
  trustedPeers:
  - veidemann-cli
  - veidemann-dashboard
  - maalfrid-gui
