# Default values for maalfrid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

.hostname: &hostname veidemann.local

.ingress: &ingress
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - *hostname
  tls:
    - secretName: local-veidemann-ingress-tls-cert
      hosts:
        - *hostname

.latest_image: &latest_image
  image:
    tag: latest
    pullPolicy: Always

config:
  rethinkdb:
    user: admin
    host: local-rethinkdb-proxy
    password: "rethinkdb"

maalfrid-service:
  <<: *latest_image
  ingress:
    <<: *ingress
  config:
    nodeEnv: development
    logLevel: debug
    pathPrefix: "/maalfrid/api"

maalfrid-gui:
  <<: *latest_image
  ingress:
    <<: *ingress
  config:
    issuer: "https://veidemann.local/dex"
    redirectUri: "https://veidemann.local/maalfrid"

maalfrid-language-detector:
  <<: *latest_image
  config:
    count: 5
    maxRecvMsgSize: "10000000"

maalfrid-initdb:
  <<: *latest_image
  config:
    rethinkdb:
      user: "admin"
      password: "rethinkdb"
    create:
      password: "notSecret"
  annotations:
    helm.sh/hook: "post-install,pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"

maalfrid-aggregator-service:
  <<: *latest_image

detect-job:
  <<: *latest_image
  cronExpression: "* */1 * * *"

aggregate-job:
  <<: *latest_image
  cronExpression: "10 */1 * * *"

sync-job:
  <<: *latest_image
  cronExpression: "*/15 * * * *"

statistics-job:
  <<: *latest_image
  cronExpression: "4 * * * *"
