apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "maalfrid-initdb.fullname" . }}
  labels:
    app: maalfrid
    component: {{ template "maalfrid-initdb.name" . }}
    chart: {{ template "maalfrid-initdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "maalfrid-initdb.fullname" . }}
    spec:
      restartPolicy: {{ .Values.image.restartPolicy | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "maalfrid.configPrefix" . }}-rethinkdb-env
                optional: false
          env:
            - name: DB_USER
              value: {{ .Values.config.rethinkdb.user | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.config.rethinkdb.password | quote }}
            - name: CREATE_DB_NAME
              value: {{ .Values.config.create.database | quote }}
            - name: CREATE_DB_USER
              value: {{ .Values.config.create.user | quote }}
            - name: CREATE_DB_PASSWORD
              value: {{ .Values.config.create.password | quote }}
