kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "maalfrid-gui.fullname" . }}
  labels:
    app: maalfrid
    component: {{ template "maalfrid-gui.name" . }}
    chart: {{ template "maalfrid-gui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  environment.json: |-
    {
      "apiUrl": "/maalfrid/api",
      "apiGatewayUrl": "/api",
      "authConfig": {
        "issuer": {{ .Values.config.issuer | quote }},
        "redirectUri": {{ .Values.config.redirectUri | quote }},
        "requireHttps": true,
        "clientId": "maalfrid-gui",
        "scope": "openid profile email groups offline_access audience:server:client_id:maalfrid-api audience:server:client_id:veidemann-api"
      }
    }
