apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "maalfrid-gui.fullname" . }}
  labels:
    app: {{ template "maalfrid-gui.name" . }}
    chart: {{ template "maalfrid-gui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "maalfrid-gui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "maalfrid-gui.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "maalfrid-gui.fullname" . }}
          items:
          - key: environment.json
            path: environment.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/maalfrid/assets/config/
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
